"""Build the weekly HTML report from a Match analysis."""

from __future__ import annotations

import json
from datetime import datetime
from html import escape

from .matcher import Analysis, Match


def _row(m: Match) -> str:
    return f"""
    <tr>
      <td>{escape(m.item.name)}</td>
      <td>{m.item.quantity:g}</td>
      <td>${m.paid_unit_price:.2f}</td>
      <td>${m.deal_unit_price:.2f}</td>
      <td><strong>${m.savings:.2f}</strong></td>
      <td>{m.receipt.purchase_date.isoformat()}</td>
      <td>{escape(m.deal.description or m.deal.item_keyword)}</td>
    </tr>
    """


def build_html(analysis: Analysis) -> str:
    eligible_rows = "".join(_row(m) for m in analysis.eligible) or (
        '<tr><td colspan="7" style="text-align:center;color:#666;padding:20px;">'
        "No items eligible for a price adjustment this week.</td></tr>"
    )
    applied_rows = "".join(_row(m) for m in analysis.already_applied) or (
        '<tr><td colspan="7" style="text-align:center;color:#666;padding:14px;">'
        "No instant-savings drops detected on recent receipts.</td></tr>"
    )
    total = analysis.total_savings
    when = datetime.now().strftime("%A, %B %d %Y at %I:%M %p")

    return f"""<!doctype html>
<html><head><meta charset="utf-8"><title>Costco Price-Adjustment Report</title></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;
             max-width:820px;margin:24px auto;color:#222;">
  <h1 style="margin:0 0 4px 0;">Weekly Costco Report</h1>
  <p style="color:#666;margin:0 0 24px 0;">{when}</p>

  <div style="background:#fff7e6;border-left:4px solid #f5a623;padding:14px 18px;border-radius:6px;margin-bottom:18px;">
    <strong>Total potential refund this week: ${total:.2f}</strong>
    across {len(analysis.eligible)} item{'s' if len(analysis.eligible) != 1 else ''}.
  </div>

  <h2 style="margin-bottom:6px;">Eligible for refund (take to membership counter)</h2>
  <table style="width:100%;border-collapse:collapse;font-size:14px;margin-bottom:28px;">
    <thead style="background:#f4f4f4;">
      <tr>
        <th style="text-align:left;padding:8px;">Item</th>
        <th style="text-align:left;padding:8px;">Qty</th>
        <th style="text-align:left;padding:8px;">You paid</th>
        <th style="text-align:left;padding:8px;">Now</th>
        <th style="text-align:left;padding:8px;">Savings</th>
        <th style="text-align:left;padding:8px;">Purchased</th>
        <th style="text-align:left;padding:8px;">Deal</th>
      </tr>
    </thead>
    <tbody>{eligible_rows}</tbody>
  </table>

  <h2 style="margin-bottom:6px;">Instant savings already applied</h2>
  <p style="color:#666;font-size:13px;margin-top:0;">
    These dropped to the deal price at checkout — nothing to do.
  </p>
  <table style="width:100%;border-collapse:collapse;font-size:14px;">
    <thead style="background:#f4f4f4;">
      <tr>
        <th style="text-align:left;padding:8px;">Item</th>
        <th style="text-align:left;padding:8px;">Qty</th>
        <th style="text-align:left;padding:8px;">Charged</th>
        <th style="text-align:left;padding:8px;">Deal</th>
        <th style="text-align:left;padding:8px;">Savings</th>
        <th style="text-align:left;padding:8px;">Purchased</th>
        <th style="text-align:left;padding:8px;">Note</th>
      </tr>
    </thead>
    <tbody>{applied_rows}</tbody>
  </table>

  <p style="color:#888;font-size:12px;margin-top:32px;">
    Generated by your local receipt-processing agent. Recognition powered by
    Anthropic Claude Haiku.
  </p>
</body></html>"""


def build_json(analysis: Analysis) -> str:
    payload = {
        "total_savings": round(analysis.total_savings, 2),
        "eligible": [
            {
                "item": m.item.name,
                "quantity": m.item.quantity,
                "paid_unit_price": m.paid_unit_price,
                "deal_unit_price": m.deal_unit_price,
                "savings": m.savings,
                "purchase_date": m.receipt.purchase_date.isoformat(),
                "deal": m.deal.description or m.deal.item_keyword,
            }
            for m in analysis.eligible
        ],
        "already_applied": [
            {
                "item": m.item.name,
                "quantity": m.item.quantity,
                "savings": m.savings,
                "purchase_date": m.receipt.purchase_date.isoformat(),
            }
            for m in analysis.already_applied
        ],
    }
    return json.dumps(payload, indent=2)
